### ISSUE TITLE
Interesting space-saver plugin

### ISSUE THREAD

**Issue by szepeviktor** [fusioneng/Unified-Post-Types#5]
I does nothing now. My mu-plugin:
```php
<?php


add_filter( 'unified_post_types', function ( $post_types ) {
    $post_types[] = 'portfolio';
    $post_types[] = 'news';
    $post_types[] = 'faq';
    $post_types[] = 'employees';
    $post_types[] = 'pricing';
    $post_types[] = 'clients';
    $post_types[] = 'testimonial';
    return $post_types;
});
```

**Comment by danielbachhuber** [comment]
> I does nothing now.

Sorry? Not sure I follow.

Do you still have the `post` post type registered?

**Comment by szepeviktor** [comment]
Yes, I do.

**Comment by szepeviktor** [comment]
What change should I see on the dashboard? Could you share a screenshot?

**Comment by szepeviktor** [comment]
None of the CPT admin pages disappeared for me.

**Comment by danielbachhuber** [comment]
Hm, not sure what the issue is. It'll eventually look like this:

![image](https://cloud.githubusercontent.com/assets/36432/7147965/c97645d0-e2b3-11e4-8756-d5a160e85a7b.png)

The plugin isn't stable yet though. I'll ping you on this thread when it is.

**Comment by szepeviktor** [comment]
http://*/wp-admin/edit.php?post_type=unified-post-types -> `Invalid post type`

**Comment by szepeviktor** [comment]
Sorry. I was on an early commit somehow. Just a few lines of code...
